### ISSUE TITLE
Add a link to this repo in the page

### ISSUE THREAD

**Issue by lizzard** [mozilla/fission-dashboard#3]
My favorite bug to file. Please add a link back to this repo into the dashboard. Or maybe I'll do it :)

**Comment by lizzard** [comment]
I can't assign myself though

**Comment by calixteman** [comment]
I just added a Github ribbon:
https://github.com/mozilla/fission-dashboard/commit/b8ef18e29d8603d7df7615b7b1cf7185e5fd276f
